export const FETCH_CHARACTER_REQUEST  = 'FETCH_CHARACTER_REQUEST'
export const FETCH_CHARACTER_SUCCESS  = 'FETCH_CHARACTER_SUCCESS'
export const FETCH_CHARACTER_ERROR  = 'FETCH_CHARACTER_ERROR'

export const FETCH_COMICS_REQUEST  = 'FETCH_COMICS_REQUEST'
export const FETCH_COMICS_SUCCESS  = 'FETCH_COMICS_SUCCESS'
export const FETCH_COMICS_ERROR  = 'FETCH_COMICS_ERROR'
